sudo: true
language: node_js
node_js:
  - '8'
cache: yarn
addons:
  apt:
    packages:
      - sshpass
install:
  - npm i npminstall && npminstall
script:
  - npm run build
after_script:
  - tar -zcvf budgerigar_api.tar.gz --exclude=*.map --exclude=node_modules --exclude=logs *
  - sshpass -p $DEPLOY_SEVER_PASSWORD scp -o StrictHostKeyChecking=no budgerigar_api.tar.gz $DEPLOY_SERVER_USER@$DEPLOY_SEVER_IP:~
  - sshpass -p $DEPLOY_SEVER_PASSWORD ssh $DEPLOY_SERVER_USER@$DEPLOY_SEVER_IP -o StrictHostKeyChecking=no "tar -zxvf budgerigar_api.tar.gz -C budgerigar_api/ && cd budgerigar_api && export BUDGERIGAR_PORT=$BUDGERIGAR_PORT && export BUDGERIGAR_SECRET_KEY=$BUDGERIGAR_SECRET_KEY && export BUDGERIGAR_DB_COLLECTION=$BUDGERIGAR_DB_COLLECTION && export BUDGERIGAR_DB_USER=$BUDGERIGAR_DB_USER && export BUDGERIGAR_DB_PASSWORD=$BUDGERIGAR_DB_PASSWORD && NODE_ENV=production && bash ./deploy.sh"
#branches:
#  only:
#  - master
